#!/bin/sh
set -e

case "$1" in
	remove|purge)
    # Remove package files.
	;;

	upgrade|abort-upgrade|abort-install|failed-upgrade|disappear)
	;;

	*)
		echo "postrm called with an unknown argument \`$1'" >&2
		exit 1
	;;
esac

exit 0