#!/bin/sh
set -e

case "$1" in
	remove)
    # Stop and disable service.
	;;

	upgrade|failed-upgrade|deconfigure)
	;;

	*)
		echo "prerm called with an unknown argument \`$1'" >&2
		exit 1
	;;
esac

exit 0
